root: true
extends: ['@typescord', prettier]
plugins: [prettier]
parserOptions:
  sourceType: 'module'
  project: packages/*/tsconfig.json
rules:
  prettier/prettier: error
  import/no-unresolved: off
env:
  node: true
